import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlarmClock,
  AlertCircleIcon,
  AlertTriangle,
  ArrowBigUpDashIcon,
  ArrowDown,
  ArrowLeftRight,
  ArrowLeftToLineIcon,
  ArrowRightToLineIcon,
  ArrowUp,
  BadgeCheck,
  BarChart3,
  BellRing,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  Component,
  Copy,
  CreditCard,
  Crop,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeIcon,
  EyeOff,
  FileTerminal,
  Filter,
  FolderOpenIcon,
  FolderPlus,
  GaugeCircle,
  GripVertical,
  Image,
  ImagePlusIcon,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MoveLeft,
  MoveRight,
  Package,
  PanelRightIcon,
  Pencil,
  PenTool,
  Plus,
  PlusCircle,
  PlusIcon,
  RefreshCw,
  RocketIcon,
  Search,
  Send,
  Settings,
  ShoppingBag,
  ShoppingCart,
  ShuffleIcon,
  Sliders,
  SlidersHorizontal,
  Star,
  SunMedium,
  Tag,
  Trash,
  Twitter,
  Undo2Icon,
  UploadCloud,
  User,
  UserCircle2,
  Volume2,
  VolumeX,
  Wallet,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  gaugeCircle: GaugeCircle,
  layoutDashboard: LayoutDashboard,
  sun: SunMedium,
  bellRing: BellRing,
  moveLeft: MoveLeft,
  moveRight: MoveRight,
  moon: Moon,
  star: Star,
  twitter: Twitter,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronUpDown: ChevronsUpDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  menu: Menu,
  verticalThreeDots: MoreVertical,
  horizontalThreeDots: MoreHorizontal,
  verticalSliders: Sliders,
  horizontalSliders: SlidersHorizontal,
  circle: Circle,
  check: Check,
  add: Plus,
  addCircle: PlusCircle,
  remove: Minus,
  view: Eye,
  hide: EyeOff,
  trash: Trash,
  edit: Edit,
  crop: Crop,
  reset: RefreshCw,
  send: Send,
  copy: Copy,
  download: Download,
  warning: AlertTriangle,
  search: Search,
  filter: Filter,
  alarm: AlarmClock,
  calendar: CalendarDays,
  user: User,
  terminal: FileTerminal,
  settings: Settings,
  logout: LogOut,
  volumne: Volume2,
  volumneMute: VolumeX,
  message: MessageSquare,
  billing: CreditCard,
  wallet: Wallet,
  dollarSign: DollarSign,
  cart: ShoppingCart,
  product: Package,
  store: ShoppingBag,
  chart: BarChart3,
  upload: UploadCloud,
  placeholder: Image,
  mail: Mail,
  externalLink: ExternalLink,
  tag: Tag,
  arrowLeftRight: ArrowLeftRight,
  badgeCheck: BadgeCheck,
  penTool: PenTool,
  activity: Activity,
  component: Component,
  userCircle: UserCircle2,
  gripVertical: GripVertical,
  pencil: Pencil,
  plus: PlusIcon,
  folderPlus: FolderPlus,
  eye: EyeIcon,
  rocket: RocketIcon,
  panelRight: PanelRightIcon,
  arrowLeft: ArrowLeftToLineIcon,
  arrowRight: ArrowRightToLineIcon,
  shuffle: ShuffleIcon,
  arrowUpDash: ArrowBigUpDashIcon,
  imagePlus: ImagePlusIcon,
  alertCircle: AlertCircleIcon,
  undo: Undo2Icon,
  folderOpen: FolderOpenIcon,
};
